export const GROUP_MAP: Record<string, string> = {
  "Mexico": "A",
  "South Africa": "A",
  "South Korea": "A",
  "Korea Republic": "A",
  "Czechia": "A",
  "Czech Republic": "A",
  "Canada": "B",
  "Bosnia and Herzegovina": "B",
  "Bosnia & Herzegovina": "B",
  "Qatar": "B",
  "Switzerland": "B",
  "Brazil": "C",
  "Morocco": "C",
  "Haiti": "C",
  "Scotland": "C",
  "United States": "D",
  "USA": "D",
  "Paraguay": "D",
  "Australia": "D",
  "Türkiye": "D",
  "Turkey": "D",
  "Germany": "E",
  "Curacao": "E",
  "Curaçao": "E",
  "Ivory Coast": "E",
  "Côte d'Ivoire": "E",
  "Ecuador": "E",
  "Netherlands": "F",
  "Japan": "F",
  "Sweden": "F",
  "Tunisia": "F",
  "Spain": "G",
  "Cape Verde": "G",
  "Cabo Verde": "G",
  "Saudi Arabia": "G",
  "Uruguay": "G",
  "Belgium": "H",
  "Egypt": "H",
  "Iran": "H",
  "New Zealand": "H",
  "France": "I",
  "Senegal": "I",
  "Iraq": "I",
  "Norway": "I",
  "Argentina": "J",
  "Algeria": "J",
  "Austria": "J",
  "Jordan": "J",
  "Portugal": "K",
  "Congo DR": "K",
  "DR Congo": "K",
  "Ghana": "K",
  "Panama": "K",
  "England": "L",
  "Croatia": "L",
  "Uzbekistan": "L",
  "Colombia": "L",
};

export const TEAM_NAME_NORMALIZE: Record<string, string> = {
  "Korea Republic": "South Korea",
  "Czech Republic": "Czechia",
  "Bosnia & Herzegovina": "Bosnia and Herzegovina",
  "USA": "United States",
  "Turkey": "Türkiye",
  "Curaçao": "Curacao",
  "Côte d'Ivoire": "Ivory Coast",
  "Cabo Verde": "Cape Verde",
  "DR Congo": "Congo DR",
};

export function normalizeTeamName(name: string): string {
  return TEAM_NAME_NORMALIZE[name] || name;
}

export function getGroup(teamName: string): string | undefined {
  return GROUP_MAP[teamName] || GROUP_MAP[normalizeTeamName(teamName)];
}
